/*
* AUTOR: DIOGO FERREIRA; GUSTAVO GUIMARÃES
* DATA : 07/03/2022
* DESC : SCRIPT DE CRIAÇÃO DAS TABELAS E A TB DICIONARIO DO CAPOS USADOS NAS TABELAS E DA
*        PROCEDURE PARA UTILIZAR O ACHARCAMPO.
*        EX: ACHARCAMPO 'DISMES_COT'
*/

USE FILTROS;
GO
--CRIAÇÃO DA TB_CAMPO----------------------------------------------------------------------------------------
IF OBJECT_ID('FILTROS.DBO.TB_CAMPO') IS NULL
BEGIN
	CREATE TABLE FILTROS.DBO.TB_CAMPO (
		IDCAMP_CAM INT IDENTITY(1,1) PRIMARY KEY,
		NOMCAM_CAM VARCHAR(MAX),
		TIPOCA_CAM VARCHAR(MAX),
		DESCCA_CAM VARCHAR(MAX),
		TBREFE_CAM VARCHAR(MAX),
		OBSERV_CAM VARCHAR(MAX)
	) ----CRIA TABELA DEFINITIVA
END
GO

INSERT INTO TB_CAMPO (
NOMCAM_CAM,
TIPOCA_CAM,
DESCCA_CAM,
TBREFE_CAM,
OBSERV_CAM)
VALUES
('IDCAMP_CAM','VARCHAR(MAX)','ID DE IDENTIFICAÇÃO','BT_CAMPO',''),
('NOMCAM_CAM','VARCHAR(MAX)','NOME DO CAMPO','TB_CAMPO',''),
('TIPOCA_CAM','VARCHAR(MAX)','TIPO DO CAMPO','TB_CAMPO',''),
('DESCCA_CAM','VARCHAR(MAX)','DESCRIÇÃO DO CAMPO','TB_CAMPO',''),
('TBREFE_CAM','VARCHAR(MAX)','TABELA ONDE O CAMPO É REFERENCIADO','TB_CAMPO',''),
('OBSERV_CAM','VARCHAR(MAX)','OBSERVAÇÕES','TB_CAMPO','')
GO

--CRIAÇÃO DA PROCEDURE --------------------------------------------------------------------------------------------
CREATE PROCEDURE ACHARCAMPO @NOME_CAMPO VARCHAR(15)
AS
SELECT * FROM TB_CAMPO(NOLOCK) WHERE NOMCAM_CAM = @NOME_CAMPO
GO
-------------------------------------------------------------------------------------------------------------------

--CRIANDO A TB_SETOR--------------------------------------------------------------------
IF OBJECT_ID('FILTROS.DBO.TB_SETOR') IS NULL
	BEGIN
		CREATE TABLE FILTROS.DBO.TB_SETOR (
			IDSETO_SET INT IDENTITY(1,1) PRIMARY KEY,
			DESSET_SET VARCHAR(MAX)
		);
	END
GO

IF NOT EXISTS(SELECT * FROM TB_CAMPO(NOLOCK) WHERE NOMCAM_CAM = 'IDSETO_SET' OR NOMCAM_CAM = 'DESSET_SET')
	BEGIN
		INSERT INTO TB_CAMPO (
		NOMCAM_CAM,
		TIPOCA_CAM,
		DESCCA_CAM,
		TBREFE_CAM,
		OBSERV_CAM)
		VALUES
		('IDSETO_SET','INT','ID DE IDENTIFICAÇÃO','TB_SETOR',''),
		('DESSET_SET','VARCHAR(MAX)','DESCRIÇÃO DO SETOR','TB_SETOR','');
	END
GO
-----------------------------------------------------------------------------------------
----CRIANDO TB_SUBSETOR -----------------------------------------------------------------
IF OBJECT_ID('FILTROS.DBO.TB_SUBSETOR') IS NULL
	BEGIN
		CREATE TABLE FILTROS.DBO.TB_SUBSETOR (
			IDSSET_SSE INT IDENTITY(1,1) PRIMARY KEY,
			IDSETO_SSE INT FOREIGN KEY REFERENCES TB_SETOR(IDSETO_SET),
			DESSSE_SSE VARCHAR(MAX)
		);
	END;
GO

IF NOT EXISTS(SELECT * FROM TB_CAMPO(NOLOCK) WHERE NOMCAM_CAM = 'IDSSET_SSE' OR NOMCAM_CAM = 'IDSETO_SSE' OR NOMCAM_CAM = 'DESSSE_SSE' )
	BEGIN
		INSERT INTO TB_CAMPO (
		NOMCAM_CAM,
		TIPOCA_CAM,
		DESCCA_CAM,
		TBREFE_CAM,
		OBSERV_CAM)
		VALUES
		('IDSSET_SSE','INT','ID DE IDENTIFICAÇÃO','TB_SUBSETOR',''),
		('IDSETO_SSE','INT','ID DE CORRELAÇÃO COM A TB_SETOR','TB_SUBSETOR',''),
		('DESSSE_SSE','VARCHAR(MAX)','DESCRIÇÃO DO SUBSETOR','TB_SUBSETOR','');
	END;
GO
-----------------------------------------------------------------------------------------
----CRIANDO TB_SEGMENTO -----------------------------------------------------------------
IF OBJECT_ID('FILTROS.DBO.TB_SEGMENTO') IS NULL
	BEGIN
		CREATE TABLE FILTROS.DBO.TB_SEGMENTO (
			IDSEGM_SEG INT IDENTITY(1,1) PRIMARY KEY,
			IDSSET_SEG INT,
			DESSEG_SEG VARCHAR(MAX)
		)
	END;
GO

IF NOT EXISTS(SELECT * FROM TB_CAMPO(NOLOCK) WHERE NOMCAM_CAM = 'IDSEGM_SEG' OR NOMCAM_CAM = 'IDSSET_SEG' OR NOMCAM_CAM = 'DESSEG_SEG')
	BEGIN
		INSERT INTO TB_CAMPO (
		NOMCAM_CAM,
		TIPOCA_CAM,
		DESCCA_CAM,
		TBREFE_CAM,
		OBSERV_CAM)
		VALUES
		('IDSEGM_SEG','INT','ID DE IDENTIFICAÇÃO','TB_SEGMENTO',''),
		('IDSSET_SEG','INT','ID DE CORRELAÇÃO COM A TB_SUBSETOR','TB_SEGMENTO',''),
		('DESSEG_SEG','VARCHAR(MAX)','DESCRIÇÃO DO SEGMENTO','TB_SEGMENTO','');
	END;
GO
-----------------------------------------------------------------------------------------
----CRIANDO A TB_EMPRESA-----------------------------------------------------------------
IF OBJECT_ID('FILTROS.DBO.TB_EMPRESA') IS NULL
	BEGIN
		CREATE TABLE FILTROS.DBO.TB_EMPRESA (
			IDEMPR_EMP INT IDENTITY(1,1) PRIMARY KEY,
			NOMEMP_EMP VARCHAR(MAX),
			CODEMP_EMP VARCHAR(20),
			CODSEG_EMP VARCHAR(20),
			IDSETO_EMP INT FOREIGN KEY REFERENCES TB_SETOR(IDSETO_SET),
			IDSSET_EMP INT FOREIGN KEY REFERENCES TB_SUBSETOR(IDSSET_SSE),
			IDSEGM_EMP INT FOREIGN KEY REFERENCES TB_SEGMENTO(IDSEGM_SEG)
		);
	END
GO

IF NOT EXISTS(SELECT * FROM TB_CAMPO(NOLOCK) WHERE NOMCAM_CAM = 'IDEMPR_EMP' OR NOMCAM_CAM = 'NOMEMP_EMP' OR NOMCAM_CAM = 'CODEMP_EMP' OR NOMCAM_CAM = 'CODSEG_EMP' OR NOMCAM_CAM = 'IDSETO_EMP'	OR NOMCAM_CAM = 'IDSSET_EMP' OR NOMCAM_CAM = 'IDSEGM_EMP')
	BEGIN
		INSERT INTO TB_CAMPO (
		NOMCAM_CAM,
		TIPOCA_CAM,
		DESCCA_CAM,
		TBREFE_CAM,
		OBSERV_CAM)
		VALUES
		('IDEMPR_EMP','INT','ID DE IDENTIFICAÇÃO','TB_EMPRESA',''),
		('NOMEMP_EMP','VARCHAR(MAX)','NOME DA EMPRESA','TB_EMPRESA',''),
		('CODEMP_EMP','VARCHAR(20)','CÓDIGO DA EMPRESA','TB_EMPRESA',''),
		('CODSEG_EMP','VARCHAR(20)','CÓDIGO DO SEGMENTO DA EMPRESA','TB_EMPRESA',''),
		('IDSETO_EMP','INT','ID DE CORRELAÇÃO COM A TB_SETOR','TB_EMPRESA',''),
		('IDSSET_EMP','INT','ID DE CORELAÇÃO COM A TB_SUBSETOR','TB_EMPRESA',''),
		('IDSEGM_EMP','INT','ID DE CORRELAÇÃO COM A TB_SEGMENTO','TB_EMPRESA','');
	END;
GO
----------------------------------------------------------------------------
/*INSERT DOS VALORES NAS TBs*/
----------------------------------------------------------------------------
--INSERT TB_SETORES---------------------------------------------------------
INSERT INTO TB_SETOR(
DESSET_SET)
VALUES
('Petróleo, Gás e Biocombustíveis'),
('Materiais Básicos'),
('Bens Industriais'),
('Consumo não Cíclico'),
('Consumo Cíclico'),
('Saúde'),
('Tecnologia da Informação'),
('Comunicações'),
('Utilidade Pública'),
('Financeiro'),
('Outros');
GO
----------------------------------------------------------------------------
--INSERT TB_SUBSETORES------------------------------------------------------
INSERT INTO TB_SUBSETOR(
IDSETO_SSE,
DESSSE_SSE)
VALUES
(1,'Petróleo, Gás e Biocombustíveis'),
(2,'Mineração'),
(2,'Siderurgia e Metalurgia'),
(2,'Químicos'),
(2,'Madeira e Papel'),
(2,'Embalagens'),
(2,'Materiais Diversos'),
(3,'Construção e Engenharia'),
(3,'Material de Transporte'),
(3,'Máquinas e Equipamentos'),
(3,'Transporte'),
(3,'Serviços Diversos'),
(3,'Comércio'),
(4,'Agropecuária'),
(4,'Alimentos Processados'),
(4,'Bebidas'),
(4,'Produtos de Uso Pessoal e de Limpeza'),
(4,'Comércio e Distribuição'),
(5,'Construção Civil'),
(5,'Tecidos, Vestuário e Calçados'),
(5,'Utilidades Domésticas'),
(5,'Automóveis e Motocicletas'),
(5,'Hoteis e Restaurantes'),
(5,'Viagens e Lazer'),
(5,'Diversos'),
(5,'Comércio'),
(6,'Medicamentos e Outros Produtos'),
(6,'Serviços Médico - Hospitalares, Análises e Diagnósticos'),
(6,'Equipamentos'),
(6,'Comércio e Distribuição'),
(7,'Computadores e Equipamentos'),
(7,'Programas e Serviços'),
(8,'Telecomunicações'),
(8,'Mídia'),
(9,'Energia Elétrica'),
(9,'Água e Saneamento'),
(9,'Gás'),
(10,'Intermediários Financeiros'),
(10,'Securitizadoras de Recebíveis'),
(10,'Serviços Financeiros Diversos'),
(10,'Previdência e Seguros'),
(10,'Exploração de Imóveis'),
(10,'Holdings Diversificadas'),
(10,'Outros Títulos'),
(11,'Outros');
GO

----------------------------------------------------------------------------
--INSERT TB_SEGMENTO--------------------------------------------------------
INSERT INTO TB_SEGMENTO(
IDSSET_SEG,
DESSEG_SEG
)
VALUES
(1,'Exploração, Refino e Distribuição'),
(1,'Equipamentos e Serviços'),
(2,'Minerais Metálicos'),
(3,'Siderurgia'),
(3,'Artefatos de Ferro e Aço'),
(3,'Artefatos de Cobre'),
(4,'Petroquímicos'),
(4,'Fertilizantes e Defensivos'),
(4,'Químicos Diversos'),
(5,'Madeira'),
(5,'Papel e Celulose'),
(6,'Embalagens'),
(7,'Materiais Diversos'),
(8,'Produtos para Construção'),
(8,'Construção Pesada'),
(8,'Engenharia Consultiva'),
(9,'Material Aeronáutico e de Defesa'),
(9,'Material Rodoviário'),
(10,'Motores, Compressores e Outros'),
(10,'Máq. e Equip. Industriais'),
(10,'Máq. e Equip. Construção e Agrícolas'),
(10,'Armas e Munições'),
(11,'Transporte Aéreo'),
(11,'Transporte Ferroviário'),
(11,'Transporte Hidroviário'),
(11,'Transporte Rodoviário'),
(11,'Exploração de Rodovias'),
(11,'Serviços de Apoio e Armazenagem'),
(12,'Serviços Diversos'),
(13,'Material de Transporte'),
(14,'Agricultura'),
(15,'Açucar e Alcool'),
(15,'Carnes e Derivados'),
(15,'Alimentos Diversos'),
(16,'Cervejas e Refrigerantes'),
(17,'Produtos de Uso Pessoal'),
(17,'Produtos de Limpeza'),
(18,'Alimentos'),
(19,'Incorporações'),
(20,'Fios e Tecidos'),
(20,'Vestuário'),
(20,'Calçados'),
(20,'Acessórios'),
(21,'Eletrodomésticos'),
(21,'Móveis'),
(21,'Utensílios Domésticos'),
(22,'Automóveis e Motocicletas'),
(23,'Hotelaria'),
(23,'Restaurante e Similares'),
(24,'Bicicletas'),
(24,'Brinquedos e Jogos'),
(24,'Produção de Eventos e Shows'),
(24,'Viagens e Turismo'),
(24,'Atividades Esportivas'),
(25,'Serviços Educacionais'),
(25,'Aluguel de carros'),
(25,'Programas de Fidelização'),
(26,'Tecidos, Vestuário e Calçados'),
(26,'Eletrodomésticos'),
(26,'Produtos Diversos'),
(27,'Medicamentos e Outros Produtos'),
(28,'Serviços Médico - Hospitalares, Análises e Diagnósticos'),
(29,'Equipamentos'),
(30,'Medicamentos e Outros Produtos'),
(31,'Computadores e Equipamentos'),
(32,'Programas e Serviços'),
(33,'Telecomunicações'),
(34,'Produção e Difusão de Filmes e Programas'),
(34,'Publicidade e Propaganda'),
(35,'Energia Elétrica'),
(36,'Água e Saneamento'),
(37,'Gás'),
(38,'Bancos'),
(38,'Soc. Crédito e Financiamento'),
(38,'Soc. Arrendamento Mercantil'),
(39,'Securitizadoras de Recebíveis'),
(40,'Gestão de Recursos e Investimentos'),
(40,'Serviços Financeiros Diversos'),
(41,'Seguradoras'),
(41,'Resseguradoras'),
(41,'Corretoras de Seguros e Resseguros'),
(42,'Exploração de Imóveis'),
(42,'Intermediação Imobiliária'),
(43,'Holdings Diversificadas'),
(44,'Outros Títulos'),
(45,'Outros');
GO
----------------------------------------------------------------------------
--INSERT TB_EMPRESA
INSERT INTO TB_EMPRESA(
NOMEMP_EMP,
CODEMP_EMP,
CODSEG_EMP,
IDSETO_EMP,
IDSSET_EMP,
IDSEGM_EMP)
VALUES
('3R PETROLEUM','RRRP','NM',1,1,1),            
('COSAN','CSAN','NM',1,1,1),             
('DOMMO','DMMO','',1,1,1),
('ENAUTA PART','ENAT','NM',1,1,1),            
('PET MANGUINH','RPMG','',1,1,1),	
('PETROBRAS','PETR','N2',1,1,1),
('PETRORECSA','RECV','NM',1,1,1),             
('PETRORIO','PRIO','NM',1,1,1),             
('ULTRAPAR','UGPA','NM',1,1,1),             
('VIBRA','VBBR','NM',1,1,1),   
('LUPATECH','LUPA','NM',1,1,2),           
('OCEANPACT','OPCT','NM',1,1,2),       
('OSX BRASIL','OSXB','NM',1,1,2),
('AURA 360','AURA','DR3',2,2,3),
('BRADESPAR','BRAP','N1 ',2,2,3),
('CBA','CBAV','NM ',2,2,3),
('CSNMINERACAO','CMIN','N2 ',2,2,3),
('LITEL','LTEL','MB ',2,2,3),
('LITELA','LTLA','MB ',2,2,3),
('MMX MINER   ','MMXM','NM ',2,2,3),
('VALE','VALE','NM ',2,2,3),
('FERBASA','FESA','N1',2,3,4),
('GERDAU','GGBR','N1',2,3,4),
('GERDAU MET','GOAU','N1',2,3,4),
('SID NACIONAL','CSNA','',2,3,4),
('USIMINAS','USIM','N1',2,3,4),
('MANGELS INDL','MGEL','',2,3,5),
('PANATLANTICA','PATI','',2,3,5),
('TEKNO','TKNO','',2,3,5),
('PARANAPANEMA','PMAM','NM',2,3,6),
('BRASKEM','BRKM','N1',2,4,7),
('DEXXOS PAR','DEXP','N1',2,4,7),
('FER HERINGER','FHER','NM',2,4,8),
('NUTRIPLANT','NUTR','MA',2,4,8),
('VITTIA','VITT','NM',2,4,8),
('CRISTAL','CRPG','',2,4,9),
('UNIPAR','UNIP','',2,4,9),
('DEXCO','DXCO','NM',2,5,10),
('EUCATEX','EUCA','N1',2,5,10),
('KLABIN S/A','KLBN','N2',2,5,11),
('MELHOR SP','MSPA','',2,5,11),
('SUZANO HOLD','NEMO','',2,5,11),
('SUZANO S.A.','SUZB','NM',2,5,11),
('IRANI','RANI','NM',2,6,12),
('METAL IGUACU','MTIG','',2,6,12),
('SANSUY','SNSY','',2,7,13),
('ETERNIT','ETER','NM',3,8,14),
('HAGA S/A','HAGA','',3,8,14),
('PORTOBELLO','PTBL','NM',3,8,14),
('AZEVEDO','AZEV','',3,8,15),
('SONDOTECNICA','SOND','',3,8,16),
('TECNOSOLO','TCNO','',3,8,16),
('EMBRAER','EMBR','NM',3,9,17),
('FRAS-LE','FRAS','N1',3,9,18),
('MARCOPOLO','POMO','N2',3,9,18),
('RANDON PART','RAPT','N1',3,9,18),
('RECRUSUL','RCSL','',3,9,18),
('RIOSULENSE','RSUL','',3,9,18),
('TUPY','TUPY','NM',3,9,18),
('WETZEL S/A','MWET','',3,9,18),
('SCHULZ','SHUL','',3,10,19),	
('WEG','WEGE','NM',3,10,19),	
('ACO ALTONA','EALT','',3,10,20),	
('AERIS	AERI','NM','',3,10,20),             
('ARMAC	ARML','NM','',3,10,20),             
('BARDELLA','BDLL','',3,10,20),
('INDS ROMI ','ROMI','NM',3,10,20),             
('INEPAR','INEP','',3,10,20),
('KEPLER WEBER','KEP','',3,10,20),
('METALFRIO','FRIO','NM',3,10,20),             
('MILLS','MILS','NM',3,10,20),             
('NORDON MET','NORD','',3,10,20),
('PRATICA','PTCA','M2',3,10,20),
('METISA','MTSA','',3,10,21),	
('STARA	STTR','MA','',3,10,21),
('TAURUS ARMAS','TASA','N2',3,10,22),        
('AZUL','AZUL','N2',3,11,23),             
('GOL','GOLL','N2',3,11,23),  
('ALL NORTE','FRRN','MB',3,11,24),             
('ALL PAULISTA','GASC','MB',3,11,24),             
('FER C ATLANT','VSPT','',3,11,24),
('MRS LOGIST','MRSA','MB',3,11,24),             
('RUMO S.A.','RAIL','NM',3,11,24),
('HIDROVIAS','HBSA','NM',3,11,25),             
('LOG-IN','LOGN','NM',3,11,25),             
('TREVISA','LUXM','	',3,11,25),
('JSL','JSLG','NM',3,11,26),             
('TEGMA','TGMA','NM',3,11,26), 
('AUTOBAN','ANHB','	',3,11,27),
('CCR SA','CCRO','NM',3,11,27),             
('CONC RAPOSO ','RPTA','	',3,11,27),
('CONC RIO TER','CRTE','MB',3,11,27),             
('ECOPISTAS','ASCP','	',3,11,27),
('ECORODOVIAS ','ECOR','NM',3,11,27),             
('ECOVIAS','ECOV','',3,11,27),
('ROD COLINAS','COLN','',3,11,27),
('ROD TIETE','RDVT','',3,11,27),
('RT BANDEIRAS','CRBD','',3,11,27),
('TRIANGULOSOL','TRIA','',3,11,27),
('TRIUNFO PART','TPIS','NM',3,11,27),             
('VIAOESTE','VOES','',3,11,27),
('GRUAIRPORT','AGRU','MB',3,11,28),             
('HMOBI S.A	','HMOB','	',3,11,28),
('INVEPAR','IVPR','MB',3,11,28),             
('PORTO VM','PSVM','',3,11,28),
('SALUS INFRA','SAIP','	',3,11,28),
('SANTOS BRP','STBP','N2',3,11,28),             
('WILSON SONS','PORT','NM',3,11,28),
('ATMASA','ATMP','NM',3,12,29),             
('BBMLOGISTICA','BBML','MA',3,12,29),
('DTCOM-DIRECT','DTCY','',3,12,29),
('ESTAPAR','ALPK','NM',3,12,29),     
('FLEX S/A','FLEX','MA',3,12,29),
('GPS','GGPS','NM',3,12,29),             
('PRINER','PRNR','MA',3,12,29),
('SEQUOIA LOG','SEQL','NM',3,12,29),             
('VALID','VLID','NM',3,12,29),
('EMBPAR S/A','EPAR','',3,13,30),	
('MINASMAQUINA','MMAQ','',3,13,30),	
('RODOBENS','RBNS','',3,13,30),	
('WLM IND COM ','WLMM','',3,13,30),	
('3TENTOS','TTEN','NM',4,14,31),             
('AGRIBRASIL','GRAO','MA',4,14,31),
('AGROGALAXY','AGXY','NM',4,14,31),             
('ALIPERTI','APTI','',4,14,31),
('BOA SAFRA','SOJA','NM',4,14,31),             
('BRASILAGRO','AGRO','NM',4,14,31),             
('POMIFRUTAS','FRTA','NM',4,14,31),             
('RAIZEN','RAIZ','N2',4,14,31),
('SLC AGRICOLA','SLCE','NM',4,14,31),             
('TERRASANTAPA','LAND','NM',4,14,31),
('JALLESMACHAD','JALL','NM',4,15,32),             
('RAIZEN ENERG','RESA','',4,15,32),
('SAO MARTINHO','SMTO','NM',4,15,32),
('BRF SA','BRFS','NM',4,15,33),             
('EXCELSIOR','BAUH','',4,15,33),
('JBS','JBSS','NM',4,15,33),             
('MARFRIG','MRFG','NM',4,15,33),             
('MINERVA','BEEF','NM',4,15,33),             
('MINUPAR','MNPR','',4,15,33),
('CAMIL	','CAML','NM',4,15,34),             
('J.MACEDO','JMCD','',4,15,34),
('JOSAPAR ','JOPA','',4,15,34),
('M.DIASBRANCO','MDIA','NM',4,15,34),             
('ODERICH','ODER','',4,15,34),
('AMBEV S/A','ABEV','',4,16,35),
('GRUPO NATURA','NTCO','NM',4,17,36), 
('BOMBRIL','BOBR','',4,17,37),
('ASSAI','ASAI','NM',4,18,38),             
('CARREFOUR BR','CRFB','NM',4,18,38),             
('GRUPO MATEUS','GMAT','NM',4,18,38),             
('P.ACUCAR-CBD','PCAR','N1',4,18,38),
('ALPHAVILLE','AVLL','NM',5,19,39),             
('CONST A LIND','CALI','',5,19,39),
('CR2','CRDE','NM',5,19,39),             
('CURY S/A','CURY','NM',5,19,39),             
('CYRELA REALT','CYRE','NM',5,19,39),             
('DIRECIONAL  ','DIRR','NM',5,19,39),             
('EVEN','EVEN','NM',5,19,39),             
('EZTEC','EZTC','NM',5,19,39),             
('GAFISA','GFSA','NM',5,19,39),             
('HELBOR','HBOR','NM',5,19,39),             
('INTER SA','INNT','MA',5,19,39),
('JHSF PART','JHSF','NM',5,19,39),             
('JOAO FORTES','JFEN','',5,19,39),
('KALLAS','KLAS','',5,19,39),
('LAVVI','LAVV','NM',5,19,39),             
('MELNICK','MELK','NM',5,19,39),             
('MITRE REALTY','MTRE','NM',5,19,39),             
('MOURA DUBEUX','MDNE','NM',5,19,39),             
('MRV','MRVE','NM',5,19,39),             
('PDG REALT','PDGR','NM',5,19,39),             
('PLANOEPLANO','PLPL','NM',5,19,39),             
('RNI','RDNI','NM',5,19,39),             
('ROSSI RESID ','RSID','NM',5,19,39),             
('TECNISA','TCSA','NM',5,19,39),             
('TEGRA INCORP','TEGA','',5,19,39),
('TENDA','TEND','NM',5,19,39),             
('TRISUL','TRIS','NM',5,19,39),             
('VIVER','VIVR','NM',5,19,39),
('CEDRO','CEDO','N1',5,20,40),             
('COTEMINAS','CTNM','',5,20,40),
('DOHLER','DOHL','',5,20,40),
('ENCORPAR','ECPR','',5,20,40),
('IND CATAGUAS','CATA','',5,20,40),
('KARSTEN','CTKA','',5,20,40),
('PETTENATI','PTNT','',5,20,40),
('SANTANENSE','CTSA','',5,20,40),
('SPRINGS','SGPS','NM',5,20,40),             
('TEKA','TEKA','',5,20,40),
('TEX RENAUX','TXRX','',5,20,40),
('TRACK FIELD','TFCO','N2',5,20,41),
('ALPARGATAS','ALPA','N1',5,20,42),             
('CAMBUCI   ','CAMB','',5,20,42),
('GRENDENE  ','GRND','NM',5,20,42),             
('VULCABRAS ','VULC','NM',5,20,42),  
('MUNDIAL','MNDL','',5,20,43),
('TECHNOS','TECN','NM',5,20,43),             
('VIVARA S.A.','VIVA','NM',5,20,43),
('WHIRLPOOL','WHRL','  ',5,21,44),
('UNICASA','UCAS','NM',5,21,45),
('HERCULES','HETA','  ',5,21,46),
('IOCHP-MAXION','MYPK','NM',5,22,47),             
('METAL LEVE  ','LEVE','NM',5,22,47),             
('PLASCAR PART','PLAS','  ',5,22,47),
('HOTEIS OTHON','HOOT','  ',5,23,48),
('BK BRASIL','BKBR','NM',5,23,49),             
('IMC S/A','MEAL','NM',5,23,49),
('BIC MONARK','BMKS','',6,24,50),
('ESTRELA','ESTR','',5,24,51),
('SPTURIS','AHEB','',5,24,52),
('TIME FOR FUN','SHOW','NM',5,24,52),  
('CVC BRASIL','CVCB','NM',5,24,53),   
('SMART FIT	','SMFT','NM',5,24,54),  
('ANIMA','ANIM','NM',5,25,55),             
('BAHEMA','BAHI','MA',5,25,55),
('COGNA ON','COGN','NM',5,25,55),             
('CRUZEIRO EDU','CSED','NM',5,25,55),             
('SER EDUCA','SEER','NM',5,25,55),             
('YDUQS PART','YDUQ','NM',5,25,55), 
('LOCALIZA','RENT','NM',5,25,56),             
('LOCAMERICA','LCAM','NM',5,25,56),             
('MAESTROLOC','MSRO','M2',5,25,56),
('MOVIDA','MOVI','NM',5,25,56),             
('UNIDAS','UNID','',5,25,56),
('VAMOS','VAMO','NM',5,25,56),      
('DOTZ SA','DOTZ','NM',5,25,57),   
('AREZZO CO','ARZZ','NM',5,26,58),             
('CEA MODAS	','CEAB','NM',5,26,58),             
('GRAZZIOTIN','CGRA','',5,26,58),
('GRUPO SOMA','SOMA','NM',5,26,58),             
('GUARARAPES','GUAR','',5,26,58),
('LE LIS BLANC','LLIS','NM',5,26,58),             
('LOJAS MARISA','AMAR','NM',5,26,58),             
('LOJAS RENNER','LREN','NM',5,26,58), 
('ALLIED','ALLD','NM',5,26,59),             
('MAGAZ LUIZA ','MGLU','NM',5,26,59),             
('VIA','VIIA','NM',5,26,59),   
('AMERICANAS','AMER','NM',5,26,60),             
('ESPACOLASER','ESPA','NM',5,26,60),             
('GRUPO SBF	','SBFG','NM',5,26,60),             
('LE BISCUIT','LLBI','',5,26,60),
('PETZ','PETZ','NM',5,26,60),             
('QUERO-QUERO','LJQQ','NM',5,26,60),             
('SARAIVA LIVR','SLED','N2',5,26,60),
('BIOMM','BIOM','MA',6,27,61),
('NORTCQUIMICA','NRTQ','MA',6,27,61),
('OUROFINO S/A','OFSA','NM',6,27,61),   
('ALLIAR','AALR','NM',6,28,62),             
('DASA','DASA','NM',6,28,62),             
('FLEURY','FLRY','NM',6,28,62),             
('HAPVIDA','HAPV','NM',6,28,62),             
('IHPARDINI','PARD','NM',6,28,62),             
('KORA SAUDE','KRSA','NM',6,28,62),             
('MATER DEI','MATD','NM',6,28,62),             
('ODONTOPREV','ODPV','NM',6,28,62),             
('ONCOCLINICAS','ONCO','NM',6,28,62),             
('QUALICORP','QUAL','NM',6,28,62),             
('REDE D OR','RDOR','NM',6,28,62),
('BAUMER','BALM','',6,29,63),
('LIFEMED	LMED','MA','',6,29,63),
('BLAU','BLAU','NM',6,30,64),             
('D1000VFARMA','DMVF','NM',6,30,64),             
('DIMED','PNVL','NM',6,30,64),             
('HYPERA','HYPE','NM',6,30,64),             
('PAGUE MENOS','PGMN','NM',6,30,64),             
('PROFARMA','PFRM','NM',6,30,64),             
('RAIADROGASIL','RADL','NM',6,30,64),             
('VIVEO','VVEO','NM',6,30,64),             
('INTELBRAS','INTB','NM',7,31,65),             
('MULTILASER','MLAS','NM',7,31,65),             
('POSITIVO TEC','POSI','NM',7,31,65),
('BEMOBI TECH','BMOB','NM',7,32,66),             
('BRQ','BRQB','MA',7,32,66),
('ENJOEI','ENJU','NM',7,32,66),             
('GETNINJAS','NINJ','NM',7,32,66),             
('INFRACOMM','IFCM','NM',7,32,66),             
('LOCAWEB','LWSA','NM',7,32,66),             
('MELIUZ','CASH','NM',7,32,66),             
('MOBLY','MBLY','NM',7,32,66),             
('MOSAICO','MOSI','NM',7,32,66),             
('NEOGRID','NGRD','NM',7,32,66),             
('PADTEC','PDTC','NM',7,32,66),             
('QUALITY SOFT','QUSW','MA',7,32,66),
('SINQIA','SQIA','NM',7,32,66),             
('TC','TRAD','NM',7,32,66),             
('TOTVS','TOTS','NM',7,32,66),             
('WDC NETWORKS','LVTC','NM',7,32,66),             
('WESTWING','WEST','NM',7,32,66),
('ALGAR TELEC','ALGT','',8,33,67),
('BRISANET','BRIT','NM',8,33,67),             
('DESKTOP','DESK','NM',8,33,67),             
('OI','OIBR','N1',8,33,67),
('TELEBRAS ','TELB','',8,33,67),
('TELEF BRASIL','VIVT','	 ',8,33,67),
('TIM','TIMS','NM',8,33,67),             
('UNIFIQUE','FIQE','NM',8,33,67),  
('CINESYSTEM','CNSY','MA',8,34,68),
('ELETROMIDIA','ELMD','NM',8,34,69),
('AES BRASIL','AESB','NM',9,35,70),             
('AES SUL','AESL','',9,35,70),
('AESOPERACOES','AESO','',9,35,70),
('AFLUENTE T','AFLT','',9,35,70),
('ALUPAR','ALUP','N2',9,35,70),     
('AMPLA ENERG ','CBEE','',9,35,70),
('CACHOEIRA	','CPTE','MB',9,35,70),             
('CEB','CEBR','',9,35,70),
('CEEE-D','CEED','',9,35,70),
('CEEE-T','EEEL','N1',9,35,70),             
('CELESC','CLSC','N2',9,35,70),             
('CELGPAR','GPAR','',9,35,70),
('CELPE','CEPE','',9,35,70),
('CEMIG','CMIG','N1',9,35,70),             
('CEMIG DIST','CMGD','',9,35,70),
('CEMIG GT','CMGT','',9,35,70),
('CESP','CESP','N1',9,35,70),             
('COELBA','CEEB','',9,35,70),
('COELCE','COCE','',9,35,70),
('COMERC PAR	','COMR','',9,35,70),
('COPEL','CPLE','N2',9,35,70),             
('COSERN','CSRN','',9,35,70),
('CPFL ENERGIA','CPFE','NM',9,35,70),             
('CPFL GERACAO','CPFG','',9,35,70),
('CPFL PIRATIN','CPFP','',9,35,70),
('CPFL RENOVAV','CPRE','',9,35,70),
('EBE','EBEN','',9,35,70),
('ELEKTRO','EKTR','',9,35,70),
('ELETROBRAS','ELET','N1',9,35,70),             
('ELETROPAR','LIPR','',9,35,70),
('EMAE','EMAE','',9,35,70),
('ENERGIAS BR ','ENBR','NM',9,35,70),             
('ENERGISA','ENGI','N2',9,35,70),             
('ENERGISA MT','ENMT','',9,35,70),
('ENERSUL','ENER','',9,35,70),
('ENEVA','ENEV','NM',9,35,70),             
('ENGIE BRASIL','EGIE','NM',9,35,70),             
('EQTL PARA	','EQPA','',9,35,70),
('EQTLMARANHAO','EQMA','MB',9,35,70),             
('EQUATORIAL  ','EQTL','NM',9,35,70),             
('ESCELSA','ESCE','',9,35,70),
('FGENERGIA	','FGEN','',9,35,70),
('GER PARANAP ','GEPA','',9,35,70),
('ITAPEBI','ITPB','',9,35,70),
('LIGHT','LIGH','',9,35,70),
('LIGHT S/A','LIGT','NM',9,35,70),             
('NEOENERGIA ','NEOE','NM',9,35,70),             
('OMEGAENERGIA','MEGA','NM',9,35,70),             
('PAUL F LUZ ','PALF','',9,35,70),
('PROMAN','PRMN','MB',9,35,70),             
('REDE ENERGIA','REDE','',9,35,70),
('RENOVA      ','RNEW','N2',9,35,70),             
('STATKRAFT	','STKF','',9,35,70),
('STO ANTONIO	','STEN','',9,35,70),
('TAESA','TAEE','N2',9,35,70),             
('TERM. PE III','TEPE','',9,35,70),
('TERMOPE','TMPE','',9,35,70),
('TRAN PAULIST','TRPL','N1',9,35,70),             
('UPTICK','UPKP','MB',9,35,70),             
('AMBIPAR','AMBP','NM',9,36,71),             
('CASAN','CASN','',9,36,71),
('COPASA','CSMG','NM',9,36,71),             
('IGUA SA','IGSN','MA',9,36,71),
('ORIZON','ORVR','NM',9,36,71),             
('SABESP','SBSP','NM',9,36,71),             
('SANEPAR','SAPR','N2',9,36,71),             
('SANESALTO','SNST','',9,36,71),	
('CEG','CEGR','',9,37,72),	
('COMGAS','CGAS','',9,37,72),	
('COMPASS','PASS','',9,37,72),	
('ABC BRASIL','ABCB','N2',10,38,73),             
('ALFA HOLDING','RPAD','',10,38,73),
('ALFA INVEST','BRIV','',10,38,73),
('AMAZONIA','BAZA','',10,38,73),
('BANCO BMG','BMGB','N1',10,38,73),             
('BANCO INTER	','BIDI','N2',10,38,73),             
('BANCO PAN','BPAN','N1',10,38,73),             
('BANESE','BGIP','',10,38,73),
('BANESTES','BEES','',10,38,73),
('BANPARA','BPAR','',10,38,73),
('BANRISUL','BRSR','N1',10,38,73),             
('BR PARTNERS	','BRBI','N2',10,38,73),             
('BRADESCO','BBDC','N1',10,38,73),             
('BRASIL','BBAS','NM',10,38,73),             
('BRB BANCO','BSLI','',10,38,73),
('BTGP BANCO	','BPAC','',10,38,73),
('ITAUSA','ITSA','N1',10,38,73),             
('ITAUUNIBANCO','ITUB','N1',10,38,73),             
('MERC BRASIL','BMEB','',10,38,73),
('MERC INVEST','BMIN','',10,38,73),
('MODALMAIS','MODL','N2',10,38,73),             
('NORD BRASIL','BNBR','',10,38,73),
('NU-NUBANK','NUBR','DR',10,38,73),
('PARANA','PRBC','',10,38,73),
('PINE','PINE','N2',10,38,73),             
('SANTANDER BR','SANB','',10,38,73),
('ALFA FINANC','CRIV','',10,38,74),
('FINANSINOS','FNCN','',10,38,74),
('MERC FINANC','MERC','',10,38,74),
('BRADESCO LSG','BDLS','',10,38,75),
('DIBENS LSG','DBEN','',10,38,75),
('BRAZIL REALT','BZRS','',10,39,76),
('BRAZILIAN SC','BSCS','',10,39,76),
('BRPR 56 SEC','WTVR','',10,39,76),
('CIBRASEC','CBSC','',10,39,76),
('ECO SEC AGRO','ECOA','MB',10,39,76),             
('GAIA AGRO','GAFL','',10,39,76),
('GAIA SECURIT','GAIA','MB',10,39,76),             
('OCTANTE SEC','OCTS','',10,39,76),
('PDG SECURIT ','PDGS','',10,39,76),
('POLO CAP SEC','PLSC','',10,39,76),
('RBCAPITALRES','RBRA','MB',10,39,76),             
('TRUESEC','APCS','',10,39,76),
('VERTCIASEC','VERT','',10,39,76),
('WTORRE PIC','WTPI','',10,39,76),
('BNDESPAR','BNDP','MB',10,40,77),             
('BRAZILIAN FR','BFRE','',10,40,77),
('G2D INVEST','G2DI','',10,40,77),
('GP INVEST','GPIV','DR',10,40,77),
('PPLA','PPLA','DR',10,40,77),
('B3 ','B3SA','NM',10,40,78),             
('BOA VISTA','BOAS','NM',10,40,78),             
('CIELO','CIEL','NM',10,40,78),             
('CLEARSALE','CLSA','NM',10,40,78),             
('CSU CARDSYST','CARD','NM',10,40,78),             
('GETNET BR','GETT','',10,40,78),
('STONE CO','STOC','DR',10,40,78),
('XP INC','XPBR','DR',10,40,78),
('ALFA CONSORC','BRGE',  '',10,41,79),
('BBSEGURIDADE','BBSE','NM',10,41,79),             
('CAIXA SEGURI','CXSE','NM',10,41,79),             
('PORTO SEGURO','PSSA','NM',10,41,79),             
('SEG AL BAHIA','CSAB',  '',10,41,79),
('SUL AMERICA ','SULA','N2',10,41,79),   
('IRBBRASIL RE','IRBR','NM',10,41,80),       
('ALPER S.A.','APER','NM',10,41,81),             
('WIZ S.A.','WIZS','NM',10,41,81), 
('ALIANSCSONAE','ALSO','NM',10,42,82),             
('BR MALLS PAR','BRML','NM',10,42,82),             
('BR PROPERT','BRPR','NM',10,42,82),             
('COR RIBEIRO ','CORR','',10,42,82),
('CYRE COM-CCP','CCPR','NM',10,42,82),             
('GENERALSHOPP','GSHP','',10,42,82),
('HABITASUL','HBTS','',10,42,82),
('HBR REALTY','HBRE','NM',10,42,82),             
('IGB S/A','IGBR','',10,42,82),
('IGUATEMI S.A','IGTI','N1',10,42,82),           
('LOG COM PROP','LOGG','NM',10,42,82),             
('MENEZES CORT','MNZC','MB',10,42,82),             
('MULTIPLAN','MULT','N2',10,42,82),             
('SAO CARLOS','SCAR','NM',10,42,82),             
('SYN PROP TEC','SYNE','NM',10,42,82), 
('BR BROKERS','BBRK','NM',10,42,83),             
('LOPES BRASIL','LPSB','NM',10,42,83), 
('MONT ARANHA','MOAR','',10,43,84),
('PAR AL BAHIA','PEAB','',10,43,84),
('SIMPAR','SIMH','NM',10,43,84),      
('CEPAC - CTBA','CTBA','MB',10,44,85),             
('CEPAC - MCRJ','MCRJ','MB',10,44,85),             
('CEPAC - PMSP','PMSP','MB',10,44,85),  
('524 PARTICIP','QVQP','MB',11,45,86),             
('ATOMPAR','ATOM','',11,45,86),
('B TECH EQI','BLUT','',11,45,86),
('BETAPART','BETP','MB',11,45,86),             
('CABINDA PART','CABI','MB',11,45,86),             
('CACONDE PART','CACO','MB',11,45,86),             
('CEMEPE','MAPT','',11,45,86),
('CIMS','CMSA','',11,45,86),
('GAMA PART','OPGM','MB',11,45,86),             
('INVEST BEMGE','FIGE','',11,45,86),
('MGI PARTICIP','MGIP','',11,45,86),
('POLPAR','PPAR','  ',11,45,86),
('PROMPT PART ','PRPT','MB',11,45,86),             
('SUDESTE S/A ','OPSE','MB',11,45,86),             
('SUL 116 PART','OPTS','MB',11,45,86),             
('YBYRA S/A	','YBRA','MB',11,45,86);          
GO
----------------------------------------------------------------------------
----CRIANDO A TB_COTA-------------------------------------------------------
IF OBJECT_ID('FILTROS.DBO.TB_COTA') IS NULL
BEGIN
	CREATE TABLE FILTROS.DBO.TB_COTA (
		IDCOTA_COT INT IDENTITY(1,1) PRIMARY KEY,
		TIPREG_COT INT,
		DTPREG_COT DATETIME,
		CODBDI_COT INT,
		CODNEG_COT VARCHAR(20),
		TPRMER_COT INT,
		NOMRES_COT VARCHAR(50),
		ESPECI_COT VARCHAR(20),
		PRAZOT_COT VARCHAR(MAX),
		MODREF_COT VARCHAR(10),
		PREABE_COT MONEY,
		PREMAX_COT MONEY,
		PREMIN_COT MONEY,
		PREMED_COT MONEY,
		PREULT_COT MONEY,
		PREOFC_COT MONEY,
		PREOFV_COT MONEY,
		TOTNEG_COT BIGINT,
		QUATOT_COT BIGINT,
		VOLTOT_COT BIGINT,
		PREEXE_COT MONEY,
		INDOPC_COT BIGINT,
		DATVEN_COT DATETIME,
		FATCOT_COT FLOAT,
		PTOEXE_COT MONEY,
		CODISI_COT VARCHAR(MAX),
		DISMES_COT BIGINT		


	)
END
GO

INSERT INTO TB_CAMPO (
NOMCAM_CAM,
TIPOCA_CAM,
DESCCA_CAM,
TBREFE_CAM,
OBSERV_CAM)
VALUES
('IDCOTA_COT', 'INT', 'ID DA TABELA COTA','TB_COTA',''),
('TIPREG_COT', 'INT', 'IPREG - TIPO DE REGISTRO','TB_COTA',''),
('DTPREG_COT', 'DATETIME','DATA DO PREGÃO','TB_COTA',''),
('CODBDI_COT', 'INT','CÓDIGO BDI','TB_COTA',''),
('CODNEG_COT', 'VARCHAR(20)','CÓDIGO DE NEGOCIAÇÃO DO PAPEL','TB_COTA',''),
('TPRMER_COT', 'INT','TIPO DE MERCADO','TB_COTA',''),
('NOMRES_COT', 'VARCHAR(50)','NOME RESUMIDO DA EMPRESSA EMISSORA DO PAPEL','TB_COTA',''),
('ESPECI_COT', 'VARCHAR(20)','ESPECIFICAÇÃO DO PAPEL','TB_COTA',''),
('PRAZOT_COT', 'VARCHAR(MAX)','PRAZO EM DIAS DO MERCADO A TERMO','TB_COTA',''),
('MODREF_COT', 'VARCHAR(10)','MOEDA DE REFERÊNCIA','TB_COTA',''),
('PREABE_COT', 'MONEY','PREÇO DE ABERTURA DO PAPELMERCADO NO PREGÃO','TB_COTA',''),
('PREMAX_COT', 'MONEY','PREÇO MÁXIMO DO PAPELMERCADO DO PREGÃO','TB_COTA',''),
('PREMIN_COT', 'MONEY','PREÇO MÍNIMO DO PAPELMERCADO NO PREGÃO','TB_COTA',''),
('PREMED_COT', 'MONEY','PREÇO MÉDIO DO PAPELMERCADO NO PREGÃO','TB_COTA',''),
('PREULT_COT', 'MONEY','PREÇO DO ÚLTIMO NÉGOCIO DO PAPELMERCADO DO PREGÃO','TB_COTA',''),
('PREOFC_COT', 'MONEY','PREÇO DA MELHOR OFERTA DE COMPRA DO PAPELMERCADO','TB_COTA',''),
('PREOFV_COT', 'MONEY','PREÇO DA MELHOR OFERTA DE VENDA DO PAPELMERCADO','TB_COTA',''),
('TOTNEG_COT', 'BIGINT','NÚMERO DE NEGÓCIOS EFETUADOS COM O PAPELMERCADO NO PREGÃO','TB_COTA',''),
('QUATOT_COT', 'BIGINT','QUANTIDADE TOTAL DE TÍTULOS NEGOCIADOS NESTE PAPELMERCADO','TB_COTA',''),
('VOLTOT_COT', 'BIGINT','VOLUME TOTAL DE TÍTULOS NEGOCIADOS NESTE PAPELMERCADO','TB_COTA',''),
('PREEXE_COT', 'MONEY','PREÇO DE EXERCÍCIO PARA O MERCADO DE OPÇÕES OU VALOR DO CONTRATO PARA O MERCADO DE TERMO SECUNDÁRIO','TB_COTA',''),
('INDOPC_COT', 'BIGINT','INDICADOR DE CORREÇÃO DE PREÇO DE EXÉRCICIOS OU VALORES DE CONTRATO PARA OS MERCADOS DE OPÇÕES OU TERMO SECUNDÁRIO','TB_COTA',''),
('DATVEN_COT', 'DATETIME','DATA DO VENCIMENTO PARA OS MERCADOS DE OPÇÕES OU TERMO SECUNDÁRIO','TB_COTA',''),
('FATCOT_COT', 'FLOAT','FATOR DE COTAÇÃO DO PAPEL','TB_COTA',''),
('PTOEXE_COT', 'BIGINT','PREÇO DE EXERCÍCIO EM PONTOS PARA OPÇÕES REFERENCIADOS EM DÓLAR OU VALOR DE CONTRATO EM PONTOS PARA TERMO SECUNDÁRIO','TB_COTA',''),
('CODISI_COT', 'VARCHAR(MAX)','CÓDIGO PAPEL NO SISTEMA ISIN OU CÓDIGO INTERNO DO PAPEL','TB_COTA',''),
('DISMES_COT', 'BIGINT','NÚMERO DE DISTRIBUIÇÃO DO PAPEL','TB_COTA','')
GO
----------------------------------------------------------------------------
----CRIANDO A TB_COTA_TB_EMPRESA--------------------------------------------
IF OBJECT_ID('FILTORS.DBO.TB_COTA_TB_EMPRESA') IS NULL
	BEGIN
		CREATE TABLE FILTROS.DBO.TB_COTA_TB_EMPRESA(
			ID INT IDENTITY(1,1) PRIMARY KEY,
			IDEMPR_CCE INT FOREIGN KEY REFERENCES TB_EMPRESA(IDEMPR_EMP),
			IDCOTA_CCE INT FOREIGN KEY REFERENCES TB_COTA(IDCOTA_COT)
		)
	END
GO

IF NOT EXISTS( SELECT * FROM TB_CAMPO(NOLOCK) WHERE NOMCAM_CAM = 'ID' OR  NOMCAM_CAM = 'IDEMPR_CCE' OR NOMCAM_CAM = 'IDCOTA_CCE')
	BEGIN
		INSERT INTO TB_CAMPO (
		NOMCAM_CAM,
		TIPOCA_CAM,
		DESCCA_CAM,
		TBREFE_CAM,
		OBSERV_CAM)
		VALUES
		('ID','INT','ID DE IDENTIFICAÇÃO','TB_COTA_TB_EMPRESA',''),
		('IDEMPR_CCE','INT','ID DE IDENTIFICAÇÃO DE CORRELAÇÃO','TB_COTA_TB_EMPRESA',''),
		('IDCOTA_CCE','INT','ID DE IDENTIFICAÇÃO DE CORRELAÇÃO','TB_COTA_TB_EMPRESA','')
	END
GO
----------------------------------------------------------------------------
